//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCRM_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int ClienteID { get; set; }
        public int ContactoID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Mobil { get; set; }
        public int PropietarioID { get; set; }
        public int CuentaID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Cuentas Cuentas { get; set; }
    }
}
