//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCRM_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.Contactos = new HashSet<Contacto>();
        }
    
        public int ClienteID { get; set; }
        public int CuentaID { get; set; }
        public string Nombre { get; set; }
        public int TipoCuentaID { get; set; }
        public string Web { get; set; }
        public string Telefono { get; set; }
        public int SectorCuentaID { get; set; }
        public Nullable<int> Empleados { get; set; }
        public int PropietarioID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contactos { get; set; }
        public virtual SectorCuenta SectorCuenta { get; set; }
        public virtual TipoCuenta TipoCuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
