//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCRM_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuentas()
        {
            this.Contactos = new HashSet<Contactos>();
        }
    
        public int ClienteID { get; set; }
        public int CuentaID { get; set; }
        public string Nombre { get; set; }
        public int TipoCuentaID { get; set; }
        public string Web { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> SectorCuentaID { get; set; }
        public Nullable<int> Empleados { get; set; }
        public Nullable<int> PropietarioID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactos> Contactos { get; set; }
    }
}
